spring:
  datasource:
    url: jdbc:mysql://mysql:3306/admin?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: admin
    password: admin
  data:
    redis:
      host: redis
      port: 6379
      database: 0
  elasticsearch:
    uris: http://elasticsearch:9200

nacos:
  server-addr: nacos:8848

rocketmq:
  endpoints: "rmq-proxy:18080"
  document-index-topic: "topic_saa_studio_document_index"
  document_index_group: "group_saa_studio_document_index"
